#
# Application Constant
#


#PROD
#google.api.key=AIzaSyDQajNmqwu5dl6tJ3nnOoYhnRl2ndchKAg

#web.linelogin = https://ca2.cubesofttech.com/lineLogin
#line.channel_id = 2010626368
#line.channel_secret = 2515d30d0772015331173d40c518117d
#line.callback_url = https://ca2.cubesofttech.com/lineCallback
#line.channel_access_token = 8bo5kJfN+pHGf9QK5+MI07Clb8fvqiM9cVdcCIJ7GwY0iCHGRj9lTJsfmo/oBlqNvB/N6IbokDq+2K3B6jXLEP6XoKJm4wQPfDMU22nW6pPQoACryNKSop2QiFWsBTM6rfGnZWZ4HW0GJ6KWtG3NcgdB04t89/1O/w1cDnyilFU=

#DEV
google.api.key=AIzaSyAahaoRphKATakHFuXS70EGQROI3VPiPBc

web.path = http://192.168.0.110:8081
web.context = http://localhost:8081
web.context2 = http://localhost:8080
web.linelogin = https://ef8c-2403-6200-88a2-6794-843c-3640-50d2-f93a.ngrok-free.app/lineLogin
line.channel_id = 2010304620
line.channel_secret = 235588ad45d974d8af659a90d138f82b
line.callback_url = https://ef8c-2403-6200-88a2-6794-843c-3640-50d2-f93a.ngrok-free.app/lineCallback
line.channel_access_token = rs8U79qmMMeADIy/MH1E6R0D0wT6KtYbueAOm/JqlybGBwU1httSlX4R6Lcz9ZoPU22xeeCXiFxF7/bHews7QCaNBxJhEbTC3MpnfWaUzE3pQ4F8t775ji27NU5WwojFFwZxEoGDXOCvnCmafZdoDAdB04t89/1O/w1cDnyilFU=

env=DEV